title: Schulte development
author: Markus Schulte
email: mail@schulte-development.de
avatar: assets/img/markus-schulte.jpg
url: "http://localhost:4000"
description: "Cloud Architect & Staff Software Engineer specializing in Azure, AWS, Java, and Golang"
keywords: "Cloud Architect, Staff Software Engineer, Self-contained Systems, Cloud-Native, Technical Leader, Azure, AWS, Java, Golang"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
remote_theme: daattali/beautiful-jekyll
navbar-links:
  About Me: "/#about-me"
  Skills: "/#my-skillset"
  Career: "/#my-career"
  Services: "/#my-services"
  Contributions: "/#my-contributions"
  Connect: "/#lets-connect"
  Imprint: "/imprint"
social-network-links:
  email: mail@schulte-development.de
  linkedin: markus-schulte
  github: SchulteDev
  stackoverflow: 1645517
