services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729" # live reload port
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  test:
    build: .
    volumes:
      - .:/app
    command: make validate
