require 'html-proofer'
require 'html-proofer-junit'
require 'fileutils'

task :test do
  options = {
    :ignore_urls => [
        /http:\/\/localhost:4000\/.*/,
        /https:\/\/outlook\.office365\.com\/.*/,
        /https:\/\/.*linkedin\.com\/.*/,
        /https:\/\/stackoverflow\.com\/.*/
    ],
    :disable_external => false
  }

  HtmlProoferJunit.run(["./_site"], options, "html-proofer.xml")
end
