name: Update CVs

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
    inputs:
      rebuild_mode:
        description: 'CV Generation Mode'
        required: true
        default: 'full_rebuild'
        type: choice
        options:
          - incremental
          - full_rebuild
      environment:
        description: 'Claude Sonnet or Opus?'
        required: true
        default: 'claude-sonnet'
        type: choice
        options:
          - claude-opus
          - claude-sonnet

env:
  CAREER_FILE: ${{ github.workspace }}/_data/career.md
  ANTI_CV_FILE: ${{ github.workspace }}/curriculum_vitae/markus-schulte-dev-anti-cv.tex
  PROFESSIONAL_CV_FILE: ${{ github.workspace }}/curriculum_vitae/markus-schulte-dev-professional-cv.tex

jobs:
  # having "changes" job instead of GitHub action paths filtering for being used as pull request check
  changes:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    outputs:
      cv: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            .github/workflows/update-cvs.yml
            _data/**
            curriculum_vitae/scripts/**
          files_ignore: |
            curriculum_vitae/*-cv.tex

  update-cvs:
    runs-on: ubuntu-latest
    needs: changes
    if: always() && (github.event_name == 'workflow_dispatch' || needs.changes.outputs.cv == 'true')
    strategy:
      matrix:
        cv_type: [ anti, professional ]
    outputs:
      mode: ${{ steps.transform.outputs.mode }}
    defaults:
      run:
        working-directory: curriculum_vitae/scripts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'curriculum_vitae/scripts/package-lock.json'
          node-version-file: 'curriculum_vitae/scripts/.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Test CV update with dry run
        env:
          DRY_RUN: true
          SKIP_API: true
        run: npm test

      - name: Transform CV with Claude
        id: transform
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          REBUILD_MODE: ${{ github.event.inputs.rebuild_mode }}
        run: npm run cv:update:${{ matrix.cv_type }}

      # - name: Validate LaTeX (compilation test)
      #   if: success() && steps.transform.outputs.mode != 'skip'
      #   uses: xu-cheng/latex-action@v3
      #   with:
      #     root_file: ${{ github.workspace }}/curriculum_vitae/markus-schulte-dev-${{ matrix.cv_type }}-cv.tex
      #     args: -lualatex -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload updated .tex file
        if: success() && steps.transform.outputs.mode != 'skip'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cv_type }}-tex-file
          path: curriculum_vitae/markus-schulte-dev-${{ matrix.cv_type }}-cv.tex
          retention-days: 7

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cv-update-logs-${{ matrix.cv_type }}-${{ github.run_id }}
          path: curriculum_vitae/scripts/tmp/
          retention-days: 7

  commit-changes:
    needs: update-cvs
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "Raw outputs: ${{ toJSON(needs.update-cvs.outputs) }}"
          echo "Mode value: '${{ needs.update-cvs.outputs.mode }}'"
          echo "Mode type: $(echo '${{ needs.update-cvs.outputs.mode }}' | wc -c)"

      - name: Check skip condition
        if: needs.update-cvs.outputs.mode != 'skip'
        run: echo "Mode is not skip, proceeding with commit"

      - name: Download updated anti CV .tex file
        uses: actions/download-artifact@v4
        with:
          name: anti-tex-file
          path: curriculum_vitae/

      - name: Download updated professional CV .tex file
        uses: actions/download-artifact@v4
        with:
          name: professional-tex-file
          path: curriculum_vitae/

      - name: Commit updated LaTeX files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "fix(cv): Update CVs (Mode: ${{ github.event.inputs.rebuild_mode == 'full_rebuild' && 'Full Rebuild' || 'Incremental Update' }})"
          file_pattern: "curriculum_vitae/markus-schulte-dev-*.tex"
